### ISSUE TITLE
Incompatible 

### ISSUE THREAD

**Issue by Twitch-Antho** [ugackMiner53/PropHunt#5]
Votre mod n'est plus compatible avec Fungle ?
Allez vous bientôt le remettre à jour ?

**Comment by AmongUsafk** [comment]
The mod has just been updated (but not released). If you check the main branch, you can see  the new comments. There are also some missing features, like custom settings that haven't been implemented in the game yet, but I know how to add them.

**Comment by ugackMiner53** [comment]
I'm actively working on a new update to make it compatible! Please be patient while I'm adding them, as it takes time to get these features done in a way that I'm happy with!

I mainly pushed the changes to main in order to show some of the new mechanics (and if anyone's desperate for an unfinished build, they can make it themselves). Thanks for the interest!

**Comment by AmongUsafk** [comment]
there is an error too when creating a lobby online : 
`[Error  :     Unity] FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.`

**Comment by Twitch-Antho** [comment]
Thank you, our Team Discord can’t wait. Could you tell me when your version will be updated. I don't know if you know this but I made a video on this mod.

**Comment by ugackMiner53** [comment]
All features of the mod are now complete! I'm very happy with the state that the mod is in! However, Among Us has updated *today*, and the modding tools are no longer compatible with the latest version. I will release the update whenever [Reactor](https://reactor.gg/) updates to the latest version!

**Comment by FangkuaiYa** [comment]
> 该模组的所有功能现已完成！我对 Mod 的状态非常满意！但是，Among Us _今天_已更新，修改工具不再与最新版本兼容。每当 [Reactor](https://reactor.gg/) 更新到最新版本时，我都会发布更新！

How to change PropHunt settings

**Comment by ugackMiner53** [comment]
@AnthoYt @FangkuaiYa 
The new update is out with release [v2024.11.5](https://github.com/ugackMiner53/PropHunt/releases/tag/v2024.11.5), compatible with `2024.10.29`!

You can change the mod settings inside the normal lobby settings menu in any Hide and Seek lobby!
